### ISSUE TITLE
Cannot install docs with Dash

### ISSUE THREAD

**Issue by jjcarstens** [NFIBrokerage/slipstream#31]
I heavily use [Dash](https://kapeli.com/dash) for local doc storage and it can't seem to download the latest versions of the hex docs. 

So..I really have no idea why this would be happening, it could be problem with dash itself. But reporting just in case there is something to fix.

FWIW `v0.5.2` was the last doc version to work. `>= 0.5.3` seems to be broken

Ill investigate a bit more, but just as an FYI for posterity..
![image](https://user-images.githubusercontent.com/11321326/109844763-af263a00-7c09-11eb-8ba0-90274a264127.png)

**Comment by jjcarstens** [comment]
So I think this might be a Dash issue being unable to handle custom sections, which is why the `Synchronous Functions` custom section doesn't work here.

I've contacted them which says responses are typically within 24 hours. Will update this when I hear something

**Comment by the-mikedavis** [comment]
oo Dash looks really cool. If I weren't on linux these days I'd be downloading it right now! :grin: 

makes sense that v0.5.3 would break it, that's when all that grouping happened: [`3ad2aef`](https://github.com/NFIBrokerage/slipstream/commit/3ad2aef853f92121c6c7ca13f93149851b7da054)

really the only reason I did that was I found that option in the ex_docs documentation and thought it was cool, but really it's totally cosmetic

I don't mind reverting [`3ad2aef`](https://github.com/NFIBrokerage/slipstream/commit/3ad2aef853f92121c6c7ca13f93149851b7da054) to unbreak your workflow, but I can hold off on that until you hear back from the Dash folks just in case they want to try it out themselves against slipstream :+1:

**Comment by jjcarstens** [comment]
So, support from Dash got back. Turns out it was a Dash error that has now been fixed 🙌
