### ISSUE TITLE
Possible incorrect documentation?

### ISSUE THREAD

**Issue by cadebward** [NFIBrokerage/slipstream#47]
Hey there! 

First off, love the library. Huge thanks for building it 👏 

Documentation in question: https://github.com/NFIBrokerage/slipstream/blob/main/lib/slipstream.ex#L537

As I'm using it, I noticed I was getting an error due to double wrapping the socket in `:ok` tuples. Is line meant to be

```elixir
@impl Slipstream
def handle_disconnect(_reason, socket) do
  reconnect(socket)
end
```

instead of `{:ok, reconnect(socket)`?

**Comment by the-mikedavis** [comment]
Ah great catch! Looks like the spec on `reconnect/1` returns `{:ok, Socket.t()}` in success so that doc line double wraps it. (Actually, it looks like `reconnect/1` is mis-spec'd too.) I'll push a commit to fix both of those 👍
